<?php
/**
 * Created by PhpStorm.
 * User: zhang
 * Date: 2019/6/3
 * Time: 21:46
 */

namespace app\controllers;


use yii\helpers\Url;
use yii\web\Controller;

class PostController extends Controller
{
    private $actionId = '';
    public function beforeAction($action)
    {
        $this->actionId = $action->id;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        //缺省路由设置： yii\web\Application::$defaultRoute
        return $this->render('index');
    }

    public function actionTest()
    {
        exit("eee");
    }

    public function actionTest2()
    {
        return "test2";
    }

    public function actionTest3()
    {
        return $this->redirect("/post/test2");
    }

    public function actionJson()
    {
        $data = ['name' => 'zhangsan', 'age' => 20];
        return $this->asJson($data);
    }

    public function actionHelloWorld()
    {
        $this->layout = false;
        return $this->render('hello-world', [
            'actionId' => $this->actionId
        ]);
    }

    public function actionUrl()
    {
        echo Url::to(['post/index'], 'https');
        echo "<br>";
        echo Url::to();

        echo "<br>";
        echo Url::home();

        echo "<br>";
        echo Url::to('/images/logo.gif', true);
    }

    public function actionView($id)
    {
        return "view: {$id}";
    }
}